### ISSUE TITLE
Consolidated list of Alyssa and Harry's suggestions

### ISSUE THREAD

**Issue by patudom** [cosmicds/minids#269]
I'm listing here the things I think we can change without confusing existing users. 

Harry:
- [x] Get rid of some of those icon+descriptions from the splash screen. No one will remember what they saw there. Axe USER GUIDE at least. Maybe learn more too.  (Pat)
- [x] In the instructional explainer, put all the icons in a fixed-width div or span so that the text that follows each icon is all left-aligned with each other vertically.  (Pat)
- [x] In the instructional explainer, set bold text for the first couple words of each description, kind of like an icon name. Explore / Select Location / Map Quiz / Learn More / Support (Pat)
- [x] Time Reset button should reset the speed too (Pat)
- [x] Maybe turn the "amount eclipsed" feature on by default? Pretty cool and helps to draw attention to the options in that box. (Pat)
- [x] Cursor for selection map should be pointer or cross-hairs, not grab hand.  (John)  (from John, use cell https://omatsuri.app/css-cursors)
- [x] Map quiz box should span same width of buttons below, ie the full width of the parent container. (John)
- [x] Give me an X out for the instructional pop-up as well (I know you can click outside but not everyone will figure that out). (John)
- [x] Make the information pop-up taller? Why do I need to scroll? (John)
- [x] X out in information popup should be embedded inside of header section, so orange line crosses full popup.  (We'll do this if we can. It may require complicated css selectors or it may be easy).
- [x] "More On Eclipses" tooltip switches to “Hide Info” tooltip. Seems unnecessary since I can’t click that button again without hiding the popup first. (John)
- [x] For the user guide, maybe the icons that are available within toggles should be depicted in the context of a toggle in the guide, so that it’s easier to find the option in the app. Not all icons are visible, like the one for horizon mode.  (Pat; put a gap between the 2 pairs of toggle instructions.)
- [x] ~~Any way to get the instructional popup back after it closes?~~  (All relevant info is in About Eclipses box, and worst case scenario someone can reload page.)
- [x] Maybe make icon for top panel a collapse arrow ^ instead of an X. Closing things can be scary!  (John)

Alyssa:
- [x] Add "not to scale" disclaimer for NASA figure  (addressed in #267)
- [x] Make share button visible all the time on Location Selector screen. If a new location hasn't been selected, the share button will share lat/long for whatever pre-set city user is on) (John, a lot in #267 already).
- [x] Add instructions about share icon once we sort out new ui   (Pat)
- [x] Figure out how to make the toggle buttons not confusing on the phone. (John, addressed in #268)

Non-actionable positive feedback from Harry:  Dang, I don’t know how y'all did it, but the eclipse functionality in horizon mode is very impressive.

Issues raised by Alyssa that I don't think we can fix now without confusing people who have already seen the app:

- Change icons.
- Get rid of map quiz?? Why?
- Make splash screen icon links - if we were to make these links, I think it will confuse the user because that would essentially bypass important info from the intro screen. None of the icons on our previous minis were links and I don't think that was an issue.

Other issues:

- [x] Link to SciAct Science Through Shadows
- [ ] #278
- [x] Make buttons user select none, so iphones don't try to give option to copy them which then blocks tooltips (John)
