### ISSUE TITLE
New RadWave SME requests

### ISSUE THREAD

**Issue by patudom** [cosmicds/minids#326]
- [x] Splashscreen - text that is currently red should be blue like the clusters. (#327) 
- [x] Modal start button - make button black with a white border (#327)
- [x] Modal image - make 2 versions to show depending on screensize. (#330)
       - current version is good for mobile
       - large screens need an image with much smaller text and possibly higher resolution if we don't think that will cause load-time problems.
- [x] Add 2 additional background options in 2d mode: (#327)
       - h-alpha
       - Planck gas & dust

- [x] Restrict zoom range in 3D mode to reasonable values for viewing Milky Way/RadWave. (On mobile, it's really easy to swipe in a way that takes you all the way to the solar system scale with no obvious fast way to get back).

**Comment by patudom** [comment]
#330 would address and close the remaining bullet item
